### ISSUE TITLE
Vrapi 2.0 unable to load 

### ISSUE THREAD

**Issue by drakosoldier298** [hammy3502/mc-vr-api#17]
https://mclo.gs/fFPRa9e
only mods running are 
optifineless vivecraft ver 0.11, architectuary, vrapi 2.0, immersivemc

seems to be complaining about how you removed vrplayer tick event

**Comment by hammy275** [comment]
mc-vr-api 2.0.0 breaks compatibility with ImmersiveMC. Am currently working on fixing it ImmersiveMC side (see https://github.com/hammy3502/immersive-mc/issues/99 ) :smile:
