### ISSUE TITLE
NonVR Crashes with ImmersiveMC

### ISSUE THREAD

**Issue by drakosoldier298** [hammy3502/mc-vr-api#18]
https://mclo.gs/xRlY8Gc

was trying to test immersive mc forgot to enable it and found out it was this. im running in nonvrmode for vivecraft, i also tested if it was vivecraft incompatible and found that it wasnt , this is the only other mod enabled.

**Comment by drakosoldier298** [comment]
Forgot to mention this is 1.18.2 forge

**Comment by hammy275** [comment]
That looks like it might be an issue with players outside of VR using the API. I'll look into it ASAP!

**Comment by hammy275** [comment]
Just confirmed this happens without Create. Not sure yet if this is an ImmersiveMC bug or a `mc-vr-api` bug, but I'm on it!

**Comment by hammy275** [comment]
Fixed in https://github.com/hammy3502/mc-vr-api/commit/04c65987ec8bde319e1544a0e237993c8112fa53 , should have it out as 2.0.0 pre-release 2 in a few

**Comment by drakosoldier298** [comment]
Seems there may still be an issue here on servers?
https://mclo.gs/ndbFdby
or might be a different mod interaction.

**Comment by drakosoldier298** [comment]
https://mclo.gs/GqmLggf
with just vivcraft architectuary and vr-api. Seems vrapi refuses to run on servers. which i guess is a nonvr.

**Comment by hammy275** [comment]
Opened this up into #19 . Thanks so much!
