### ISSUE TITLE
Fix isLeftHanded function.

### ISSUE THREAD

**Issue by yohlimem** [hammy3502/mc-vr-api#28]
```
    public boolean isLeftHanded(PlayerEntity player) {
        if (player.world.isClient) {
            VRDataGrabber.isSelf(player);
            return VRDataGrabber.isLeftHanded();
        } else {
            return ((Tracker.ServerSideVRPlayerData)Tracker.playerToVR.get(player.getGameProfile().getName())).isLeftHanded();
        }
    }
```

in         
```
if (player.world.isClient) {
            VRDataGrabber.isSelf(player);
            return VRDataGrabber.isLeftHanded();
}
```

it returns the function  `VRDataGrabber.isLeftHanded();` but if the player is not using VR it returns nothing: 
```
    public static boolean isLeftHanded() {
        if (!ReflectionConstants.clientHasVivecraft()) {
            throw new IllegalArgumentException("Cannot retrieve hand status of player outside VR!");
        } else {
            try {
                Object VRSettingsInstance = Minecraft_VRSettings.get(vrHolder);
                return (Boolean)VRSettings_reverseHands.get(VRSettingsInstance);
            } catch (IllegalAccessException var1) {
                throw new RuntimeException("Could not get handedness of local player!");
            }
        }
    }
```
as you can see here
```
if (!ReflectionConstants.clientHasVivecraft()) {
            throw new IllegalArgumentException("Cannot retrieve hand status of player outside VR!");
}
```
ReflectionConstants.clientHasVivecraft() is true only if the player is using VR
if it doesn't the API's funtion will return an error: 
```java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1141)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at net.blf02.vrapi.client.VRDataGrabber.isLeftHanded(VRDataGrabber.java:210)
	at net.blf02.vrapi.common.VRAPI.isLeftHanded(VRAPI.java:206)
```

now I'm not sure if this is just my code or for everyones' but for me, this is what happens, please fix this
the code where the error occurs:
 ` Vec3d controllerVel = (VRPlugin.apiInstance.getRenderVRPlayer().getController(VRPlugin.apiInstance.isLeftHanded(player) ? 1 : 0).position().subtract(lastControllerPos)).multiply(100d);
`

fix: 
```
        if (player.world.isClient) {
            VRDataGrabber.isSelf(player);
            try{
                 return VRDataGrabber.isLeftHanded();
            } catch (RuntimeException re){
                return null;
            }
            
            } else {
               return ((Tracker.ServerSideVRPlayerData)Tracker.playerToVR.get(player.getGameProfile().getName())).isLeftHanded();
           }

```

**Comment by hammy275** [comment]
This is very intentional behavior. You should use `playerInVR()` to check if the player is in VR before performing a left-handed check on them.

We can't return `null` from a function that returns a `boolean` (as it's a primitive), and I'm not keen on returning `Boolean` objects here to allow for that (especially considering one can just check if a player is in VR before checking if they're left-handed).

Leaving this issue open for further discussion, however if I were to modify this method to not crash, I think it'd make more sense to return some sensible default rather than returning `null` to avoid inevitable `NullPointerException`s down the road for people.

**Comment by hammy275** [comment]
I'm actually going to close this issue. If anyone wants to see `mc-vr-api` made to always return values rather than `null`s/throw exceptions, I'd be interested!
