### ISSUE TITLE
MC-VR-API is not found on this server. 1.19.2 servers

### ISSUE THREAD

**Issue by GrayKnight-CC** [hammy3502/mc-vr-api#34]
So i have this persistant problem where i put the fabric version of this mod and i try to play in a server it says that it cant be found even thought i installed immersive mc and installed mc-vr- api i have no idea what is going on and i am wondering if there is a fix

**Comment by hammy275** [comment]
Please upload your server's log to https://mclo.gs, then send it to me here or on Discord (hammy275#9444), so I can help to debug the issue.

Please also send me the exact filenames for ImmersiveMC and MC VR API as they are in your `mods` folder

**Comment by GrayKnight-CC** [comment]
so I Mannage to fix this problem by installing a later version and re-installing architectury
