### ISSUE TITLE
When using vr-api as a dependency, the 'runServer' of Gradle cannot be executed

### ISSUE THREAD

**Issue by Mafuyu33** [hammy3502/mc-vr-api#45]
Log: https://mclo.gs/KWSAG5e  
  
I tested it in an example mod where nothing has been changed, using Fabric version 1.20.4. Then I added the dependencies of vr-api and architectury, but encountered errors when running the 'runServer' command (which was working before adding the vr-api dependency).  
  
Does this mean that using vr-api as a dependency in a mod will prevent it from running on the physics server side? What if I want to add a mod that has a dependency on vr-api in Minecraft Server?  
  
It could be caused by this part？IDK
![1](https://github.com/hammy275/mc-vr-api/assets/134225805/7afb073d-c7d1-4965-85ef-d40901a234bd)  
Log Picture:  
![2](https://github.com/hammy275/mc-vr-api/assets/134225805/5f83cb9f-f305-4fb0-8dac-8441c1f84553)

**Comment by hammy275** [comment]
This has been fixed and released as version 3.0.8. As of writing, it should be up on Modrinth, and will be up on CurseForge once it's approved. Thank you for reporting this :smile:.
